### ISSUE TITLE
Using protected charts in CompositionDefinitions

### ISSUE THREAD

**Issue by alfredo-milani-kiratech** [krateoplatformops/core-provider#27]
**Is your feature request related to a problem? Please describe.**
Is it possible to specify in a CompositionDefinition a Chart that needs authentication ?

How is it possible to specify the secrets required to access this possible private Chart ?

<img width="583" alt="image" src="https://github.com/krateoplatformops/core-provider/assets/145569086/aae17444-329a-4fd5-ae19-5591be80ec35">

**Comment by braghettos** [comment]
Fixed with release https://github.com/krateoplatformops/core-provider/actions/runs/9204285745
